name: LaTeX Build

on:
  workflow_dispatch:
  push:
    paths:
      - documento/arquivoPrincipal.tex

jobs:
  build:
    runs-on: ubuntu-latest
    name: LaTex Build Procedure
    steps:
    - name: Replace docker by podman
      run: |
        sudo apt update
        sudo apt -y purge docker*
        sudo apt -y install podman
    - name: Repo checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Cache podman
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-podman
        restore-keys: ${{ runner.os }}-podman
        path: |
          ~/.local/share/containers
    - name: Cache Miktex Config
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-dot_miktex
        restore-keys: ${{ runner.os }}-dot_miktex
        path: |
          dot_miktex
    - name: Force 777 permission to document dir
      run: chmod 777 documento dot_miktex
    - name: Build PDF with make clean pdf
      run: make on_docker
    - name: Upload PDF to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: "Build do PDF"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: documento/arquivoPrincipal.pdf
        asset_name: documento.pdf
        tag: ${{ github.ref }}
        overwrite: true
